# Generated by Django 5.2.8 on 2025-11-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="os",
            options={"verbose_name_plural": "Operating Systems"},
        ),
    ]
