# Generated by Django 5.2.8 on 2026-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinstance",
            name="actual_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual time spent on this activity in hours",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated time to complete this work order in hours",
                max_digits=5,
                null=True,
            ),
        ),
    ]
