# Generated by Django 5.2.8 on 2025-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="threshold_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Optional thresholds for this task, e.g. {"max_days_overdue": 7, "window": "30d"}',
                null=True,
            ),
        ),
    ]
